export const autofillProductsEN = [
  { title: "Anchovy" },
  { title: "Apple" },
  { title: "Artichoke" },
  { title: "Asparagus" },
  { title: "Avocado" },
  { title: "Baby food" },
  { title: "Bacon" },
  { title: "Basil" },
  { title: "Bean" },
  { title: "Beer" },
  { title: "Blueberry" },
  { title: "Bread" },
  { title: "Brownie" },
  { title: "Butter" },
  { title: "Cabbage" },
  { title: "Carrot" },
  { title: "Cauliflower" },
  { title: "Celery" },
  { title: "Cereal" },
  { title: "Champagne" },
  { title: "Chicken" },
  { title: "Coconut milk" },
  { title: "Coffee" },
  { title: "Corn" },
  { title: "Cranberry" },
  { title: "Cottage cheese" },
  { title: "Cream" },
  { title: "Dill" },
  { title: "Doughnut" },
  { title: "Duck" },
  { title: "Egg" },
  { title: "Eggplant" },
  { title: "Fennel" },
  { title: "Feta" },
  { title: "Fish" },
  { title: "Flour" },
  { title: "Frozen vegetables" },
  { title: "Garlic" },
  { title: "Ginger" },
  { title: "Grape" },
  { title: "Greek yogurt" },
  { title: "Granola" },
  { title: "Green tea" },
  { title: "Hazelnut" },
  { title: "Herb" },
  { title: "Honey" },
  { title: "Hot sauce" },
  { title: "Hummus" },
  { title: "Ice cream" },
  { title: "Instant noodles" },
  { title: "Iced tea" },
  { title: "Jam" },
  { title: "Jalapeño" },
  { title: "Jerky" },
  { title: "Juice" },
  { title: "Kiwi" },
  { title: "Kimchi" },
  { title: "Ketchup" },
  { title: "Kielbasa" },
  { title: "Lasagna noodles" },
  { title: "Lard" },
  { title: "Leek" },
  { title: "Lemon" },
  { title: "Lentil" },
  { title: "Lettuce" },
  { title: "Lime" },
  { title: "Lollipop" },
  { title: "Macaroni" },
  { title: "Mackerel" },
  { title: "Mango" },
  { title: "Maple syrup" },
  { title: "Melon" },
  { title: "Milk" },
  { title: "Molasses" },
  { title: "Mushroom" },
  { title: "Muesli" },
  { title: "Nectarine" },
  { title: "Noodle" },
  { title: "Nut" },
  { title: "Nut butter" },
  { title: "Nutella" },
  { title: "Oat" },
  { title: "Olive" },
  { title: "Olive oil" },
  { title: "Onion" },
  { title: "Orange" },
  { title: "Oregano" },
  { title: "Oyster sauce" },
  { title: "Pancake mix" },
  { title: "Paprika" },
  { title: "Pita bread" },
  { title: "Parmesan cheese" },
  { title: "Pea" },
  { title: "Pickle" },
  { title: "Pineapple" },
  { title: "Pepper" },
  { title: "Potato" },
  { title: "Quinoa" },
  { title: "Quick oats" },
  { title: "Raisin" },
  { title: "Radish" },
  { title: "Red cabbage" },
  { title: "Rosemary" },
  { title: "Salmon" },
  { title: "Salsa" },
  { title: "Sausage" },
  { title: "Shrimp" },
  { title: "Sour cream" },
  { title: "Soy sauce" },
  { title: "Spaghetti" },
  { title: "Spinach" },
  { title: "Strawberry" },
  { title: "Tabasco sauce" },
  { title: "Tangerine" },
  { title: "Tea" },
  { title: "Thyme" },
  { title: "Tomato" },
  { title: "Tortillas" },
  { title: "Turkey" },
  { title: "Tuna" },
  { title: "Udon noodle" },
  { title: "Vanilla extract" },
  { title: "Vermicelli noodle" },
  { title: "Vinegar" },
  { title: "Walnut" },
  { title: "Wasabi" },
  { title: "Watermelon" },
  { title: "Whipped cream" },
  { title: "Wine" },
  { title: "Yogurt" },
  { title: "Zest" },
  { title: "Zucchini" },
];

export const autofillProductsUA = [
  { title: "Авокадо" },
  { title: "Ананас" },
  { title: "Анчоус" },
  { title: "Апельсин" },
  { title: "Арахіс" },
  { title: "Арахісова паста" },
  { title: "Артишок" },
  { title: "Базилік" },
  { title: "Баклажан" },
  { title: "Бекон" },
  { title: "Васабі" },
  { title: "Вермішель" },
  { title: "Вершки" },
  { title: "Вино" },
  { title: "Випічка" },
  { title: "Гарбуз" },
  { title: "Горіх" },
  { title: "Горошок" },
  { title: "Гранола" },
  { title: "Гречка" },
  { title: "Гриби" },
  { title: "Груша" },
  { title: "Гірчиця" },
  { title: "Джем" },
  { title: "Дитяча їжа" },
  { title: "Диня" },
  { title: "Екстракт ванилі" },
  { title: "Закуски" },
  { title: "Заморожені овочі" },
  { title: "Збиті вершки" },
  { title: "Згущенка" },
  { title: "Зелений чай" },
  { title: "Зелень" },
  { title: "Йогурт" },
  { title: "Ізюм" },
  { title: "Імбир" },
  { title: "Індичка" },
  { title: "Кава" },
  { title: "Кавун" },
  { title: "Капуста" },
  { title: "Картопля" },
  { title: "Качка" },
  { title: "Квасоля" },
  { title: "Кетчуп" },
  { title: "Кефір" },
  { title: "Кислі огірки" },
  { title: "Копченості" },
  { title: "Креветки" },
  { title: "Кріп" },
  { title: "Кукурудза" },
  { title: "Курятина" },
  { title: "Ківі" },
  { title: "Кіноа" },
  { title: "Лайм" },
  { title: "Лапша" },
  { title: "Лимон" },
  { title: "Листя салату" },
  { title: "Лосось" },
  { title: "Льодяники" },
  { title: "Макарони" },
  { title: "Малина" },
  { title: "Манго" },
  { title: "Мандарини" },
  { title: "Масло" },
  { title: "Мед" },
  { title: "Молоко" },
  { title: "Морква" },
  { title: "Морозиво" },
  { title: "Мюслі" },
  { title: "Мівіна" },
  { title: "Нектарін" },
  { title: "Нутелла" },
  { title: "Оливки" },
  { title: "Оливкова олія" },
  { title: "Олія" },
  { title: "Орегано" },
  { title: "Оцет" },
  { title: "Паприка" },
  { title: "Пармезан" },
  { title: "Пекінська капуста" },
  { title: "Перець" },
  { title: "Петрушка" },
  { title: "Печиво" },
  { title: "Пиво" },
  { title: "Пластівці" },
  { title: "Полуниця" },
  { title: "Помідор" },
  { title: "Піта" },
  { title: "Редис" },
  { title: "Риба" },
  { title: "Розмарин" },
  { title: "Рукола" },
  { title: "Салат латук" },
  { title: "Сало" },
  { title: "Селера" },
  { title: "Сир" },
  { title: "Сироп" },
  { title: "Сметана" },
  { title: "Солодощі" },
  { title: "Сосиски" },
  { title: "Соус" },
  { title: "Соус табаско" },
  { title: "Соєвий соус" },
  { title: "Спагетті" },
  { title: "Спаржа" },
  { title: "Сік" },
  { title: "Тортилья" },
  { title: "Тунець" },
  { title: "Фета" },
  { title: "Халапеньо" },
  { title: "Хліб" },
  { title: "Хумус" },
  { title: "Цвітна капуста" },
  { title: "Цедра" },
  { title: "Цибуля" },
  { title: "Цукіні" },
  { title: "Чай" },
  { title: "Часник" },
  { title: "Чорний чай" },
  { title: "Чорниця" },
  { title: "Шампанське" },
  { title: "Шоколад" },
  { title: "Шпинат" },
  { title: "Яблука" },
  { title: "Яйця" },
];
